### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by felipecrs** [AntoineGS/teams-status-rs#1]
I think it would be nice to manage the service through a tray icon. There is a Rust library for that:

https://github.com/olback/tray-item-rs

**Comment by AntoineGS** [comment]
There is a tray icon! ;)
That is actually the library that I used.
If you are not seeing the tray icon it probably means the application did not start properly, there is an output.log file where you are running the exe that will hopefully contain some useful logs as to why it is not.

**Comment by felipecrs** [comment]
Oh, I am very sorry. I did not try your project yet, I just thought you didn't have done it yet. lol

My bad, completely.

**Comment by AntoineGS** [comment]
No worries 😉

**Comment by felipecrs** [comment]
Just to say that I tried it out today and it works great. Thanks a lot!

**Comment by AntoineGS** [comment]
Glad to hear, thanks for the feedback!
