### ISSUE TITLE
Addition of remaining binary sensors

### ISSUE THREAD

**Issue by linickx** [AntoineGS/teams-status-rs#10]
Hello,
Thank you, this little app is just what I need!

Is it possible to have a sensor setup for mute? e.g `binary_sensor.teams_mute`

**Comment by AntoineGS** [comment]
Sure I can add it 🙂

**Comment by Romanmir** [comment]
I would like to expand on this a bit to include all sensors that are returned by the API.
Thoughts? The use case would be simply for more monitoring options.

**Comment by AntoineGS** [comment]
I had told myself I would add them when someone wants them, I guess this is it! 😂

**Comment by AntoineGS** [comment]
Changes done in v0.3.0!
Let me know if you run into any issues, the MQTT has not been tested as I am not currently set up for it.
I have been using the HA portion all day though and it has been working pretty well.
There does seem to be an issue with the background-blur on the Teams side, it does seem to report all changes but there is nothing I can do for that.
Commit: https://github.com/AntoineGS/teams-status-rs/commit/9a0ce6ed534392f6e8143199e35d3b5c736c9aae

**Comment by Romanmir** [comment]
Thank you, I won't have a chance to test it until work tomorrow.

**Comment by Romanmir** [comment]
Confirmed, I can see the rest of the sensors in HA. Thank you.

**Comment by AntoineGS** [comment]
Thanks for the feedback!
